### ISSUE TITLE
Here's why new website is not active

### ISSUE THREAD

**Issue by adamazad** [PreventFlashLoanAttacks/Prevent-Flash-Loan-Attacks#12]
GitHub uses a `CNAME` file to determine which branch to use for the domain pointing to the repository. We have two of those:

1. [`main > docs/CNAME`](https://github.com/PreventFlashLoanAttacks/Prevent-Flash-Loan-Attacks/blob/1f4804d/docs/CNAME)
2. [`gh-pages > CNAME`](https://github.com/PreventFlashLoanAttacks/Prevent-Flash-Loan-Attacks/blob/gh-pages/cname)

GitHub is using the `main` branch as the source for GitHub pages. @PatrickAlphaC, see the settings.

**Comment by PatrickAlphaC** [comment]
I'll be testing this again today. There was that issue I had before so I reverted the changes.

**Comment by PatrickAlphaC** [comment]
I was also just thinking of maybe just doing https://www.mkdocs.org/ that way we can make additional pages easier. What do you think @adamazad ?

**Comment by adamazad** [comment]
@PatrickAlphaC, making additional pages in Gatsby is even easier! In fact, the current version has 7 pages. 

Each `ts` and `mdx` file can be viewed. For instance, you can view `more-details.mdx` by going to `/more-details`. I did not use a layout for those. I opted for a single-page information webpage to buy time.

There's also a table of content if you hover on the left side of the page -- it's a hidden gem
