### ISSUE TITLE
Add Pickle Finance attack

### ISSUE THREAD

**Issue by adamazad** [PreventFlashLoanAttacks/Prevent-Flash-Loan-Attacks#5]
> It appears we may have just seen our latest DeFi flash loan attack.
> $20m in DAI stolen - potentially the biggest flash loan attack since Harvest a month ago, which took $30m in stables.
> (h/t to @mattybchats for spotting this tx)

[Nick C. (@n2ckchong) on Twitter](https://twitter.com/n2ckchong/status/1330232388425838592)

Transaction https://etherscan.io/tx/0xe72d4e7ba9b5af0cf2a8cfb1e30fd9f388df0ab3da79790be842bfbed11087b0

**Comment by PatrickAlphaC** [comment]
Holy shit

**Comment by jimtje** [comment]
Not a flash loan attack. Poor validation, sure, but attacker basically created their own token for the attack, not a loan.

https://ethtx.info/mainnet/0xe72d4e7ba9b5af0cf2a8cfb1e30fd9f388df0ab3da79790be842bfbed11087b0

https://bloxy.info/tx/0xe72d4e7ba9b5af0cf2a8cfb1e30fd9f388df0ab3da79790be842bfbed11087b0

**Comment by adamazad** [comment]
Thank you for the update!
