### ISSUE TITLE
Proposal to add CONTRIBUTING.md

### ISSUE THREAD

**Issue by adamazad** [PreventFlashLoanAttacks/Prevent-Flash-Loan-Attacks#6]
At the moment, there is no `CONTRIBUTING.md` file. I propose to create a one indicating how to add new reports via issues (template) or a PR.

If we use Gatsby, the steps are as follows:

1. Fork this repo
2. Create a new branch.
3. Edit `src/pages/historic-attacks.mdx`. It is a markdown file. Add your record to the table.
4. Once, finished, create a PR against this repo.

Of course, you are welcome to open a new issue to report attacks, propose changes, and improve the initiative.

**Comment by PatrickAlphaC** [comment]
Agreed. We can split the contributing docs to their own section.

**Comment by adamazad** [comment]
As addressed in #4
